# Generated by Django 2.1.7 on 2019-04-20 02:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Appeal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='授課名稱')),
                ('code', models.IntegerField(verbose_name='選課代碼')),
                ('number', models.IntegerField(verbose_name='編號')),
                ('depiction', models.TextField()),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='課程名稱')),
                ('teacher', models.CharField(max_length=255, verbose_name='授課教授')),
                ('code', models.IntegerField()),
                ('class_time', models.CharField(max_length=255, verbose_name='修課時間')),
                ('grade', models.DecimalField(decimal_places=1, max_digits=2)),
                ('comment', models.TextField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
