# Generated by Django 2.1.7 on 2019-05-11 08:53

import blog.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='clove',
            field=blog.models.ListField(blank=True),
        ),
    ]
